{
  "chaoslib-version": "1.21.0",
  "platform": "Windows-10-10.0.19042-SP0",
  "node": "LNAR-5CD9051V6X",
  "experiment": {
    "title": "Test Steady state",
    "description": "N/A",
    "tags": [],
    "steady-state-hypothesis": {
      "title": "actuator-test",
      "probes": [
        {
          "type": "probe",
          "name": "all_microservices_healthy",
          "provider": {
            "type": "python",
            "module": "chaosk8s.probes",
            "func": "all_microservices_healthy",
            "arguments": {
              "ns": "default"
            }
          },
          "tolerance": "true"
        }
      ]
    },
    "method": [],
    "dry": false
  },
  "start": "2021-10-10T15:41:27.108751",
  "status": "failed",
  "deviated": false,
  "steady_states": {
    "before": {
      "steady_state_met": false,
      "probes": [
        {
          "activity": {
            "type": "probe",
            "name": "all_microservices_healthy",
            "provider": {
              "type": "python",
              "module": "chaosk8s.probes",
              "func": "all_microservices_healthy",
              "arguments": {
                "ns": "default"
              }
            },
            "tolerance": "true"
          },
          "output": null,
          "status": "failed",
          "exception": [
            "Traceback (most recent call last):\n",
            "  File \"C:\\Users\\asunder\\.venvs\\chaostk\\lib\\site-packages\\chaoslib\\provider\\python.py\", line 55, in run_python_activity\n    return func(**arguments)\n",
            "  File \"C:\\Users\\asunder\\.venvs\\chaostk\\lib\\site-packages\\chaosk8s\\probes.py\", line 26, in all_microservices_healthy\n    return all_pods_healthy(ns, secrets)\n",
            "  File \"C:\\Users\\asunder\\.venvs\\chaostk\\lib\\site-packages\\chaosk8s\\pod\\probes.py\", line 269, in all_pods_healthy\n    ret = v1.list_namespaced_pod(namespace=ns)\n",
            "  File \"C:\\Users\\asunder\\.venvs\\chaostk\\lib\\site-packages\\kubernetes\\client\\api\\core_v1_api.py\", line 15302, in list_namespaced_pod\n    return self.list_namespaced_pod_with_http_info(namespace, **kwargs)  # noqa: E501\n",
            "  File \"C:\\Users\\asunder\\.venvs\\chaostk\\lib\\site-packages\\kubernetes\\client\\api\\core_v1_api.py\", line 15413, in list_namespaced_pod_with_http_info\n    return self.api_client.call_api(\n",
            "  File \"C:\\Users\\asunder\\.venvs\\chaostk\\lib\\site-packages\\kubernetes\\client\\api_client.py\", line 348, in call_api\n    return self.__call_api(resource_path, method,\n",
            "  File \"C:\\Users\\asunder\\.venvs\\chaostk\\lib\\site-packages\\kubernetes\\client\\api_client.py\", line 180, in __call_api\n    response_data = self.request(\n",
            "  File \"C:\\Users\\asunder\\.venvs\\chaostk\\lib\\site-packages\\kubernetes\\client\\api_client.py\", line 373, in request\n    return self.rest_client.GET(url,\n",
            "  File \"C:\\Users\\asunder\\.venvs\\chaostk\\lib\\site-packages\\kubernetes\\client\\rest.py\", line 239, in GET\n    return self.request(\"GET\", url,\n",
            "  File \"C:\\Users\\asunder\\.venvs\\chaostk\\lib\\site-packages\\kubernetes\\client\\rest.py\", line 233, in request\n    raise ApiException(http_resp=r)\n",
            "kubernetes.client.exceptions.ApiException: (404)\nReason: Not Found\nHTTP response headers: HTTPHeaderDict({'Server': 'Microsoft-IIS/10.0', 'Date': 'Sun, 10 Oct 2021 15:41:27 GMT', 'Content-Length': '0'})\n\n",
            "\nDuring handling of the above exception, another exception occurred:\n\n",
            "chaoslib.exceptions.ActivityFailed: kubernetes.client.exceptions.ApiException: (404)\nReason: Not Found\nHTTP response headers: HTTPHeaderDict({'Server': 'Microsoft-IIS/10.0', 'Date': 'Sun, 10 Oct 2021 15:41:27 GMT', 'Content-Length': '0'})\n"
          ],
          "start": "2021-10-10T15:41:27.109765",
          "end": "2021-10-10T15:41:27.125080",
          "duration": 0.015315,
          "tolerance_met": false
        }
      ]
    },
    "after": null,
    "during": []
  },
  "run": [],
  "rollbacks": [],
  "end": "2021-10-10T15:41:27.126095",
  "duration": 0.017343759536743164
}